#!/usr/bin/expect  

set timeout 120
set file_path [lindex $argv 0]

if { $file_path == "" } {
    set file_path "english.json"
}

# start
spawn ./build/simulate.sh
expect "Welcome to ChCore shell!"
# run anything you like here
# interact
send -- "test_json.bin $file_path 0 \n"
expect "done"
sleep 1
send -- "test_json.bin $file_path 1 \n"
expect "done"
sleep 1
send -- "test_json.bin $file_path 2 \n"
expect "done"
sleep 1
exit
