chcore_config(CHCORE_CROSS_COMPILE STRING "" "Prefix for cross compiling toolchain")
chcore_config(CHCORE_PLAT STRING "" "Target hardware platform")
chcore_config(CHCORE_CHPM_INSTALL_PREFIX PATH ".chpm/install" "Install prefix of ChPM (for using packages installed by ChPM)")
chcore_config(CHCORE_CHPM_INSTALL_TO_RAMDISK BOOL OFF "Copy installed ChPM packages to ramdisk?")
chcore_config(CHCORE_VERBOSE_BUILD BOOL OFF "Generate verbose build log?")
chcore_config(CHCORE_QEMU_SDCARD_IMG PATH "" "Path to SD card image file for QEMU (raspi3)")
chcore_config(CHCORE_ENABLE_FMAP BOOL ON "Enable file fd mmap?")
chcore_config(CHCORE_IPC_PERF_ENABLED BOOL OFF "Enable IPC performance measurement?")

chcore_config_include(kernel/config.cmake)
chcore_config_include(user/config.cmake)
