#!/usr/bin/expect  

# include the config file
source ./dsm-scripts/tests/config.exp

set timeout 60

# Check if a program was passed as the first argument, otherwise use default
if {[llength $argv] == 0} {
    set program $default_program
} else {
    set program [lindex $argv 0]
}

# Check if the program_name is in the config list
if {![info exists program_names($program)]} {
    puts "Error: program '$program' is not in the config list."
    exit 1
}

# Get the program_name from the program_names array
set program_name $program_names($program)

# start
spawn ./build/simulate.sh 1
expect "Welcome to ChCore shell!"

# restore the program
send -- "restore_process.bin $program_name & \r"

interact
