#!/usr/bin/expect  

set default_program "hello"

array set program_names {
    "hello" "test_cfork_hello.bin"
    "leveldb" "leveldb-dbbench"
    "matmul" "test_matmul.bin"
    "linpack" "test_linpack.bin"
    "float" "test_float.bin"
    "json" "test_json.bin"
    "pyaes" "test_pyaes.bin"
    # ...
}

array set program_args {
    "hello" ""
    "leveldb" "--benchmarks=fillbatch --num=1000000"
    "matmul" "2000 2"
    "linpack" "2000 2"
    "float" "10000000 2"
    "json" "english.json 2"
    "pyaes" "2000000 100 2"
    # ...
}
# "leveldb" "--benchmarks=fillbatch --num=1000000"
# ...

array set program_expects {
    "hello" "[1]"
    "leveldb" "version"
    "float" "Running /test_float.bin"
    "json" "Running /test_json.bin"
    "pyaes" "Running /test_pyaes.bin"
    # ...
}
