#!/usr/bin/expect  

set timeout 60
set thread_num [lindex $argv 0]

if { $thread_num == "" } {
    set thread_num 1
}

# start
spawn ./build/simulate.sh
expect "Welcome to ChCore shell!"
# run anything you like here
# interact
send -- "kmeans -p 100000 -t $thread_num -m 1 \n"
send -- "kmeans -p 100000 -t $thread_num -m 1 \n"
send -- "kmeans -p 100000 -t $thread_num -m 2 \n"
send -- "kmeans -p 100000 -t $thread_num -m 2 \n"
expect "done"
expect "done"
expect "done"
expect "done"
exit

interact
