#!/usr/bin/expect  

set timeout 120
set thread_num [lindex $argv 0]

if { $thread_num == "" } {
    set thread_num 1
}

# start
spawn ./build/simulate.sh
expect "Welcome to ChCore shell!"
# run anything you like here
# interact
send -- "string_match -f key_file_100MB.txt -t $thread_num -m 1 \n"
send -- "string_match -f key_file_100MB.txt -t $thread_num -m 1 \n"
send -- "string_match -f key_file_100MB.txt -t $thread_num -m 2 \n"
send -- "string_match -f key_file_100MB.txt -t $thread_num -m 2 \n"
expect "done"
expect "done"
expect "done"
expect "done"
exit