chcore_config(CHCORE_DEMOS_LIGRA BOOL OFF "Build ligra?")
chcore_config(CHCORE_DEMOS_REDIS BOOL OFF "Build redis?")
# chcore_config(CHCORE_DEMOS_LIBEVENT BOOL OFF "Build libevent? Already installed in Docker")
chcore_config(CHCORE_DEMOS_MEMCACHED BOOL OFF "Build memcached?")
chcore_config(CHCORE_DEMOS_MEMCACHETEST BOOL OFF "Build memcache test?")
chcore_config(CHCORE_DEMOS_SQLITE BOOL OFF "Build SQLite3?")
chcore_config(CHCORE_DEMOS_LEVELDB BOOL OFF "Build LevelDB?")
chcore_config(CHCORE_DEMOS_YCSB BOOL OFF "Build YCSB-C?")
chcore_config(CHCORE_DEMOS_PHOENIX BOOL OFF "Build Phoenix?")
chcore_config(CHCORE_DEMOS_ROCKSDB BOOL OFF "Build RocksDB?")
chcore_config(CHCORE_DEMOS_GEMM BOOL OFF "Build GEMM?")
