chcore_config(CHCORE_KERNEL_DEBUG BOOL ON "Build debug version of the kernel?")
chcore_config(CHCORE_KERNEL_TEST BOOL OFF "Enable kernel tests?")
chcore_config(CHCORE_KERNEL_VIRT BOOL OFF "Enable virtualization support in kernel?")
chcore_config(CHCORE_KERNEL_RT BOOL OFF "Enable realtime support in kernel?")
chcore_config(CHCORE_SLS BOOL OFF "Enable Single level store support?")
chcore_config(CHCORE_SSI BOOL ON "Enable using CXL Memory?")
chcore_config(CHCORE_SSI_SLS BOOL OFF "Enable Single level store support?")
chcore_config(CHCORE_IPC_PERF BOOL OFF "Performance test for IPC?")
