chcore_config(CHCORE_KERNEL_DEBUG BOOL ON "Build debug version of the kernel?")
chcore_config(CHCORE_KERNEL_TEST BOOL OFF "Enable kernel tests?")
chcore_config(CHCORE_KERNEL_VIRT BOOL OFF "Enable virtualization support in kernel?")
chcore_config(CHCORE_KERNEL_RT BOOL OFF "Enable realtime support in kernel?")
chcore_config(CHCORE_SLS BOOL OFF "Enable Single level store support?")
chcore_config(CHCORE_SSI BOOL ON "Enable using CXL Memory?")
chcore_config(CHCORE_SSI_SLS BOOL ON "Enable Single level store support?")
chcore_config(CHCORE_PLAT_CPU_NUM STRING "12" "Compile-time max CPU number (PLAT_CPU_NUM)")
