# DSM_SHM_DEVICE:
# "IVSHMEM_NUMA" or "CXL_NUMA" or "CXL"
set(DSM_SHM_DEVICE "IVSHMEM")
# DSM_MALLOC_MODE 
# "CXL": all on CXL
# "DRAM": all on DRAM
# "MIXED": our target partten
set(DSM_MALLOC_MODE "MIXED")

set(DSM_THREADCTX_MODE "DRAM")
set(DSM_PGTABLE_MODE "DRAM")
set(DSM_STACK_MODE "DRAM")
