/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_ACCEPT4

#define HAVE_MEMFD_CREATE

#define HAVE_MKOSTEMP

#define HAVE_POSIX_FALLOCATE

#define HAVE_PRCTL

#define HAVE_STRNDUP

#define HAVE_SYS_PRCTL_H

#define PACKAGE "wayland"

#define PACKAGE_VERSION "1.19.90"
