#!/usr/bin/env python3
"""
Generate kernel/tests/tst_malloc_data.c for the random get_pages/free_pages test.

Op codes stored directly (no % 4 needed in C):
  0 = alloc-4K   (get_pages order 0)
  1 = alloc-2M   (get_pages order 9)
  2 = free-4K    (free top of 4K stack; alloc if empty)
  3 = free-2M    (free top of 2M stack; alloc if empty)

Sequence is balanced so that alloc/free counts stay roughly even and
stacks stay well within RANDOM_MF_CAP_4K=8192 / RANDOM_MF_CAP_2M=256.
"""

import random
import argparse
import os

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False

MALLOC_DATA_NUM = 95000
CAP_4K = 8192
CAP_2M = 256
WEIGHTS = [1, 1, 1, 1]

OUT_C   = os.path.join(os.path.dirname(__file__), "tst_malloc_data.c")
OUT_PNG = os.path.join(os.path.dirname(__file__), "tst_malloc_data_ops.png")

OP_NAMES = ["alloc-4K", "alloc-2M", "free-4K", "free-2M"]


def generate(n, seed=42):
    rng = random.Random(seed)
    ops = []
    n4 = 0
    n2 = 0
    for _ in range(n):
        w = list(WEIGHTS)
        if n4 >= CAP_4K:
            w[0] = 0
        if n2 >= CAP_2M:
            w[1] = 0
        if n4 == 0:
            w[2] = 0
        if n2 == 0:
            w[3] = 0
        if sum(w) == 0:
            w = list(WEIGHTS)
        op = rng.choices([0, 1, 2, 3], weights=w)[0]
        ops.append(op)
        if op == 0:
            n4 += 1
        elif op == 1:
            n2 += 1
        elif op == 2 and n4 > 0:
            n4 -= 1
        elif op == 3 and n2 > 0:
            n2 -= 1
    return ops


def write_c(ops, path):
    with open(path, "w") as f:
        f.write("/* Auto-generated by gen_random_mf_data.py -- do not edit. */\n")
        f.write("/* Op codes: 0=alloc-4K  1=alloc-2M  2=free-4K  3=free-2M  */\n")
        f.write("int malloc_data[] = {")
        per_line = 20
        for i, v in enumerate(ops):
            if i % per_line == 0:
                f.write("\n\t")
            f.write(f"{v},")
        f.write("\n};\n")


def plot(ops, path):
    from collections import Counter
    counts = Counter(ops)
    labels = [OP_NAMES[i] for i in range(4)]
    values = [counts[i] for i in range(4)]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    ax = axes[0]
    bars = ax.bar(labels, values,
                  color=["#4c72b0", "#dd8452", "#55a868", "#c44e52"])
    ax.set_title("Op distribution (count)")
    ax.set_ylabel("Count")
    for bar, v in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 50,
                f"{v}\n({v / len(ops) * 100:.1f}%)",
                ha="center", va="bottom", fontsize=9)

    ax2 = axes[1]
    n4, n2 = 0, 0
    s4, s2, xs = [0], [0], [0]
    step = max(1, len(ops) // 500)
    for i, op in enumerate(ops):
        if op == 0:
            n4 += 1
        elif op == 1:
            n2 += 1
        elif op == 2 and n4 > 0:
            n4 -= 1
        elif op == 3 and n2 > 0:
            n2 -= 1
        if (i + 1) % step == 0:
            xs.append(i + 1)
            s4.append(n4)
            s2.append(n2)
    ax2.plot(xs, s4, label="4K stack depth", color="#4c72b0")
    ax2.plot(xs, s2, label="2M stack depth", color="#dd8452")
    ax2.axhline(CAP_4K, color="#4c72b0", linestyle="--", alpha=0.4,
                label=f"cap 4K={CAP_4K}")
    ax2.axhline(CAP_2M, color="#dd8452", linestyle="--", alpha=0.4,
                label=f"cap 2M={CAP_2M}")
    ax2.set_title("Stack depth over time")
    ax2.set_xlabel("iteration")
    ax2.set_ylabel("depth")
    ax2.legend(fontsize=8)

    fig.suptitle(f"tst_malloc_data  n={len(ops)}")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    print(f"Plot saved: {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=MALLOC_DATA_NUM)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--no-plot", action="store_true")
    args = parser.parse_args()

    print(f"Generating {args.n} ops (seed={args.seed})...")
    ops = generate(args.n, args.seed)

    from collections import Counter
    counts = Counter(ops)
    for i, name in enumerate(OP_NAMES):
        print(f"  {name}: {counts[i]} ({counts[i] / len(ops) * 100:.1f}%)")

    write_c(ops, OUT_C)
    print(f"Written: {OUT_C}")

    if not args.no_plot:
        if HAS_MPL:
            plot(ops, OUT_PNG)
        else:
            print("matplotlib not available, skipping plot.")


if __name__ == "__main__":
    main()
